export * from './shared/data-base';
export {
  FATWA_BASE,
  HADITH_BASE,
  BOOKS_BASE,
  ADHKAR_BASE,
  dataUrl,
  hadithUrl,
  booksUrl,
  adhkarUrl,
  shardUrl,
  isRemoteData,
  booksIndexUrl,
  booksShardUrl,
  hadithBookIndexUrl,
  hadithBookMetadataUrl,
  hadithChapterUrl,
  hadithBookTocUrl,
  hadithSharhUrl,
} from './shared/data-base';
