export interface FeaturedClassic {
  id: string;
  shamelaId?: number;
  title: string;
  author: string;
  authorDeath: string;
  discipline: string;
  artTag: string;
  volumes: number;
  description: string;
  gradient: string;
  accent: string;
  icon: string;
}

export const FEATURED_ISLAMIC_CLASSICS: FeaturedClassic[] = [
  {
    id: 'shamela-1167',
    shamelaId: 1167,
    title: 'صحيح البخاري',
    author: 'الإمام محمد بن إسماعيل البخاري',
    authorDeath: 'ت ٢٥٦ هـ',
    discipline: 'كتب السنة',
    artTag: 'hadith',
    volumes: 9,
    description: 'أصح كتاب بعد كتاب الله تعالى، ديوان السنة النبوية المسندة المحققة على النسخة السلطانية.',
    gradient: 'from-amber-950 via-stone-900 to-emerald-950',
    accent: '#f59e0b',
    icon: '📜',
  },
  {
    id: 'book-sahih-muslim',
    title: 'صحيح مسلم',
    author: 'الإمام مسلم بن الحجاج النيسابوري',
    authorDeath: 'ت ٢٦١ هـ',
    discipline: 'كتب السنة',
    artTag: 'hadith',
    volumes: 5,
    description: 'المسند الصحيح المختصر بنقل العدل عن العدل، المتميز بحسن الصنعة والترتيب الفقهي.',
    gradient: 'from-teal-950 via-stone-900 to-amber-950',
    accent: '#14b8a6',
    icon: '✨',
  },
  {
    id: 'shamela-308',
    shamelaId: 308,
    title: 'تفسير القرآن العظيم (ابن كثير)',
    author: 'الحافظ عماد الدين ابن كثير',
    authorDeath: 'ت ٧٧٤ هـ',
    discipline: 'التفسير',
    artTag: 'quran',
    volumes: 8,
    description: 'عمدة كتب التفسير بالمأثور، يجمع بين تفسير القرآن بالقرآن وبالسنة وأقوال الصحابة والتابعين.',
    gradient: 'from-emerald-950 via-slate-900 to-teal-950',
    accent: '#10b981',
    icon: '📖',
  },
  {
    id: 'shamela-287',
    shamelaId: 287,
    title: 'زاد المعاد في هدي خير العباد',
    author: 'الإمام شمس الدين ابن قيم الجوزية',
    authorDeath: 'ت ٧٥١ هـ',
    discipline: 'السيرة والفقه',
    artTag: 'fiqh',
    volumes: 5,
    description: 'الموسوعة الفريدة في فقه السيرة النبوية واستنباط الأحكام الشرعية والتربوية والطبية.',
    gradient: 'from-amber-950 via-stone-900 to-yellow-950',
    accent: '#d97706',
    icon: '🏰',
  },
  {
    id: 'shamela-1681',
    shamelaId: 1681,
    title: 'المجموع شرح المهذب',
    author: 'الإمام محيي الدين النووي',
    authorDeath: 'ت ٦٧٦ هـ',
    discipline: 'الفقه الشافعي والمقارن',
    artTag: 'fiqh',
    volumes: 23,
    description: 'أعظم موسوعات الفقه المقارن في الإسلام، يحرر أقوال الأئمة الأربعة وأدلتهم بعين الإنصاف.',
    gradient: 'from-cyan-950 via-stone-900 to-emerald-950',
    accent: '#06b6d4',
    icon: '⚖️',
  },
  {
    id: 'shamela-1755',
    shamelaId: 1755,
    title: 'المغني في فقه الإمام أحمد',
    author: 'الإمام موفق الدين ابن قدامة المقدسي',
    authorDeath: 'ت ٦٢٠ هـ',
    discipline: 'الفقه الحنبلي والمقارن',
    artTag: 'fiqh',
    volumes: 15,
    description: 'تاج كتب الفقه الحنبلي والمرجع الأول في الخلاف العالي واستدلالات فقهاء السلف.',
    gradient: 'from-emerald-950 via-stone-900 to-teal-950',
    accent: '#059669',
    icon: '🏛️',
  },
  {
    id: 'shamela-12',
    shamelaId: 12,
    title: 'العقيدة الواسطية',
    author: 'شيخ الإسلام ابن تيمية',
    authorDeath: 'ت ٧٢٨ هـ',
    discipline: 'العقيدة والتوحيد',
    artTag: 'aqeedah',
    volumes: 1,
    description: 'الرسالة الذهبية الجامعة لمعتقد أهل السنة والجماعة في أسماء الله وصفاته واليوم الآخر.',
    gradient: 'from-rose-950 via-stone-900 to-amber-950',
    accent: '#f43f5e',
    icon: '🛡️',
  },
  {
    id: 'shamela-2601',
    shamelaId: 2601,
    title: 'سير أعلام النبلاء',
    author: 'الإمام شمس الدين الذهبي',
    authorDeath: 'ت ٧٤٨ هـ',
    discipline: 'التراجم والطبقات',
    artTag: 'history',
    volumes: 25,
    description: 'الموسوعة التاريخية الكبرى في تراجم أئمة الإسلام والملوك والخلفاء والقراء والفقهاء.',
    gradient: 'from-stone-950 via-amber-950 to-stone-900',
    accent: '#b45309',
    icon: '📜',
  },
  {
    id: 'shamela-2901',
    shamelaId: 2901,
    title: 'لسان العرب',
    author: 'العلامة جمال الدين ابن منظور',
    authorDeath: 'ت ٧١١ هـ',
    discipline: 'اللغة والمعاجم',
    artTag: 'language',
    volumes: 15,
    description: 'أوسع وأجل معاجم العربية، جمع فيه مصنفات القدماء في مفردات لسان الضاد.',
    gradient: 'from-violet-950 via-stone-900 to-emerald-950',
    accent: '#8b5cf6',
    icon: '✒️',
  },
  {
    id: 'quran-hafs',
    title: 'مصحف المدينة النبوية',
    author: 'مجمع الملك فهد لطباعة المصحف الشريف',
    authorDeath: 'القراءات المتواترة',
    discipline: 'المصاحف الشريفة',
    artTag: 'quran',
    volumes: 1,
    description: 'المصحف الشريف برواية حفص عن عاصم من طريق الشاطبية، خط عثمان طه فائق الدقة والإتقان.',
    gradient: 'from-amber-950 via-emerald-950 to-stone-900',
    accent: '#fbbf24',
    icon: '🌟',
  },
];
