export interface HadithBookMeta {
  id: string;
  nameAr: string;
  nameEn: string;
  authorAr: string;
  authorEn: string;
  fileName: string;
  hadithCount: number;
  featured?: boolean;
  category: 'sahih' | 'sunan' | 'masanid' | 'jawami' | 'forties' | 'akhlak';
  description: string;
}

export const HADITH_BOOKS_LIST: HadithBookMeta[] = [
  {
    id: 'bukhari',
    nameAr: 'صحيح البخاري',
    nameEn: 'Sahih al-Bukhari',
    authorAr: 'الإمام محمد بن إسماعيل البخاري (ت ٢٥٦ هـ)',
    authorEn: 'Imam Muhammad ibn Ismail al-Bukhari',
    fileName: 'bukhari.json',
    hadithCount: 7277,
    featured: true,
    category: 'sahih',
    description: 'أصح كتاب بعد كتاب الله عز وجل، جامع للأحاديث الصحيحة المسندة في العقائد والأحكام والرقائق.',
  },
  {
    id: 'muslim',
    nameAr: 'صحيح مسلم',
    nameEn: 'Sahih Muslim',
    authorAr: 'الإمام مسلم بن الحجاج النيسابوري (ت ٢٦١ هـ)',
    authorEn: 'Imam Muslim ibn al-Hajjaj',
    fileName: 'muslim.json',
    hadithCount: 5362,
    featured: true,
    category: 'sahih',
    description: 'ثاني أصح دواوين السنة النبوية، متميز بحسن الترتيب والصياغة وجمع طرق الحديث في موضع واحد.',
  },
  {
    id: 'abudawud',
    nameAr: 'سنن أبي داود',
    nameEn: 'Sunan Abi Dawud',
    authorAr: 'الإمام أبو داود السجستاني (ت ٢٧٥ هـ)',
    authorEn: 'Imam Abu Dawud al-Sijistani',
    fileName: 'abudawud.json',
    hadithCount: 5274,
    category: 'sunan',
    description: 'أعظم كتب أحاديث الأحكام الفقهية، يجمع سنن النبي صلى الله عليه وسلم وأقضيته.',
  },
  {
    id: 'tirmidhi',
    nameAr: 'جامع الترمذي',
    nameEn: 'Jami` at-Tirmidhi',
    authorAr: 'الإمام أبو عيسى محمد بن عيسى الترمذي (ت ٢٧٩ هـ)',
    authorEn: 'Imam Abu Isa at-Tirmidhi',
    fileName: 'tirmidhi.json',
    hadithCount: 3956,
    category: 'sunan',
    description: 'يتميز ببيان درجة الحديث وعلله ومذاهب الفقهاء من الصحابة والتابعين والأئمة.',
  },
  {
    id: 'nasai',
    nameAr: 'سنن النسائي (المجتبى)',
    nameEn: 'Sunan an-Nasa\'i',
    authorAr: 'الإمام أحمد بن شعيب النسائي (ت ٣٠٣ هـ)',
    authorEn: 'Imam Ahmad an-Nasa\'i',
    fileName: 'nasai.json',
    hadithCount: 5758,
    category: 'sunan',
    description: 'أقل كتب السنن أحاديث ضعيفة بعد الصحيحين، متميز بدقة التبويب ونقد الأسانيد.',
  },
  {
    id: 'ibnmajah',
    nameAr: 'سنن ابن ماجه',
    nameEn: 'Sunan Ibn Majah',
    authorAr: 'الإمام محمد بن يزيد بن ماجه القزويني (ت ٢٧٣ هـ)',
    authorEn: 'Imam Muhammad ibn Majah',
    fileName: 'ibnmajah.json',
    hadithCount: 4341,
    category: 'sunan',
    description: 'رابع كتب السنن ومتمم الكتب الستة، يمتاز ببراعة ترتيب الأبواب الفقهية.',
  },
  {
    id: 'malik',
    nameAr: 'موطأ الإمام مالك',
    nameEn: 'Muwatta Malik',
    authorAr: 'الإمام مالك بن أنس إمام دار الهجرة (ت ١٧٩ هـ)',
    authorEn: 'Imam Malik ibn Anas',
    fileName: 'malik.json',
    hadithCount: 1858,
    featured: true,
    category: 'jawami',
    description: 'أول كتاب صُنّف في الحديث والفقه المبوب، نال ثناء أئمة الإسلام عبر القرون.',
  },
  {
    id: 'ahmed',
    nameAr: 'مسند الإمام أحمد',
    nameEn: 'Musnad Ahmad ibn Hanbal',
    authorAr: 'الإمام أحمد بن حنبل إمام أهل السنة (ت ٢٤١ هـ)',
    authorEn: 'Imam Ahmad ibn Hanbal',
    fileName: 'ahmed.json',
    hadithCount: 26363,
    category: 'masanid',
    description: 'أعظم وأشمل موسوعة مسندية في الإسلام، مرتبة على مسانيد الصحابة رضي الله عنهم.',
  },
  {
    id: 'darimi',
    nameAr: 'سنن الدارمي',
    nameEn: 'Sunan al-Darimi',
    authorAr: 'الإمام عبد الله بن عبد الرحمن الدارمي (ت ٢٥٥ هـ)',
    authorEn: 'Imam Abdullah al-Darimi',
    fileName: 'darimi.json',
    hadithCount: 3503,
    category: 'sunan',
    description: 'ديوان جليل افتتحه بمقدمة في فضل العلم وآدابه واتباع السنة.',
  },
  {
    id: 'riyad_assalihin',
    nameAr: 'رياض الصالحين',
    nameEn: 'Riyad as-Salihin',
    authorAr: 'الإمام يحيى بن شرف النووي (ت ٦٧٦ هـ)',
    authorEn: 'Imam Yahya ibn Sharaf an-Nawawi',
    fileName: 'riyad_assalihin.json',
    hadithCount: 1896,
    featured: true,
    category: 'akhlak',
    description: 'أشهر وأبرك كتب تزكية النفوس والأخلاق والآداب والترغيب والترهيب.',
  },
  {
    id: 'bulugh_almaram',
    nameAr: 'بلوغ المرام من أدلة الأحكام',
    nameEn: 'Bulugh al-Maram',
    authorAr: 'الحافظ ابن حجر العسقلاني (ت ٨٥٢ هـ)',
    authorEn: 'Al-Hafiz Ibn Hajar al-Asqalani',
    fileName: 'bulugh_almaram.json',
    hadithCount: 1568,
    category: 'jawami',
    description: 'عمدة طلاب الفقه في أحاديث الأحكام الفقهية مع بيان درجتها وتخريجها بدقة.',
  },
  {
    id: 'aladab_almufrad',
    nameAr: 'الأدب المفرد',
    nameEn: 'Al-Adab al-Mufrad',
    authorAr: 'الإمام محمد بن إسماعيل البخاري (ت ٢٥٦ هـ)',
    authorEn: 'Imam al-Bukhari',
    fileName: 'aladab_almufrad.json',
    hadithCount: 1322,
    category: 'akhlak',
    description: 'موسوعة البخاري الكبرى في بر الوالدين وصلة الأرحام ومكارم الأخلاق.',
  },
  {
    id: 'shamail_muhammadiyah',
    nameAr: 'الشمائل المحمدية',
    nameEn: 'Ash-Shama\'il al-Muhammadiyyah',
    authorAr: 'الإمام أبو عيسى الترمذي (ت ٢٧٩ هـ)',
    authorEn: 'Imam at-Tirmidhi',
    fileName: 'shamail_muhammadiyah.json',
    hadithCount: 399,
    category: 'akhlak',
    description: 'أبدع ما كتب في صفات النبي صلى الله عليه وسلم الخَلقية والخُلقية وسيرته العطرة.',
  },
  {
    id: 'mishkat_almasabih',
    nameAr: 'مشكاة المصابيح',
    nameEn: 'Mishkat al-Masabih',
    authorAr: 'الخطيب التبريزي (ت ٧٤١ هـ)',
    authorEn: 'Al-Khatib at-Tibrizi',
    fileName: 'mishkat_almasabih.json',
    hadithCount: 5945,
    category: 'jawami',
    description: 'جمع فيه أحاديث المصابيح وزاد عليها وأخرجها من أصول كتب السنة المعتمدة.',
  },
  {
    id: 'nawawi40',
    nameAr: 'الأربعون النووية',
    nameEn: 'The Forty Hadith of an-Nawawi',
    authorAr: 'الإمام يحيى بن شرف النووي (ت ٦٧٦ هـ)',
    authorEn: 'Imam an-Nawawi',
    fileName: 'nawawi40.json',
    hadithCount: 42,
    featured: true,
    category: 'forties',
    description: 'الأحاديث الجوامع التي عليها مدار الإسلام وقواعد الدين.',
  },
  {
    id: 'qudsi40',
    nameAr: 'الأحاديث القدسية (الأربعون)',
    nameEn: 'Forty Hadith Qudsi',
    authorAr: 'جمع من المحدثين',
    authorEn: 'Compilation of Hadith Qudsi',
    fileName: 'qudsi40.json',
    hadithCount: 40,
    category: 'forties',
    description: 'أحاديث نبوية شريفة يرويها النبي صلى الله عليه وسلم عن ربه تبارك وتعالى.',
  },
  {
    id: 'shahwaliullah40',
    nameAr: 'الأربعون لولي الله الدهلوي',
    nameEn: 'Forty Hadith of Shah Waliullah',
    authorAr: 'الإمام شاه ولي الله الدهلوي (ت ١١٧٦ هـ)',
    authorEn: 'Shah Waliullah Dehlawi',
    fileName: 'shahwaliullah40.json',
    hadithCount: 40,
    category: 'forties',
    description: 'أربعون حديثاً مسندة بأسانيد متصلة شريفة في جوامع الكلم والآداب.',
  },
];
