/**
 * Compatibility facade for Hadith domain libraries and engines.
 * Canonical implementation lives in @/features/hadith.
 */
export {
  HADITH_BOOKS_LIST,
  GRADE_FILTER_OPTIONS,
  COMMON_STOP_WORDS,
  extractCleanMatn,
  prepareBookData,
  loadHadithBook,
  loadHadithBookFromShards,
  loadSpecificHadith,
  clearBookCache,
  getBookCacheSize,
  buildSharhInvertedIndex,
  loadHadeethEncSharh,
  findHadithSharh,
  getSharhByHadithId,
  clearSharhCache,
  isSharhCacheLoaded,
  parseMicroIndexPayload,
  loadHadithMicroIndex,
  searchHadithsInBook,
  searchAcrossAllBooks,
  loadSunanGrades,
  getHadithGrade,
  isMuttafaqunAlayh,
  parseHadithIsnad,
  findNarratorBio,
  HADITH_INTENT_CLUSTERS,
  extractQueryCore,
  expandSemanticTerms,
  resolveSemanticConcept,
  FAKE_HADITH_CATEGORIES,
  loadFakeHadiths,
  searchFakeHadiths,
  checkHadithAuthenticity,
  SUPPORTED_TRANSLATION_LANGUAGES,
  isBookTranslationAvailable,
  fetchHadithTranslation,
  getCachedHadithBook,
  setCachedHadithBook,
  BUILTIN_SEED_SHARH,
  useHadithStore,
  HadithHubView,
  HadithCard,
  HadithDetailModal,
  HadithSearchHeader,
  HadithBookSelectorModal,
  HadithChapterSelectorModal,
  HadithGradesGuideModal,
  HadithIsnadTree,
  NarratorBioModal,
  FakeHadithChecker,
  HadithTranslationsView,
  type HadithBookMeta,
  type HadithItem,
  type HadithChapter,
  type HadithBookData,
  type HadeethEncSharhItem,
  type GlobalSearchResultItem,
  type NarratorScholarlyOpinion,
  type NarratorProfile,
  type IsnadNodeRole,
  type IsnadNode,
  type ParsedIsnad,
  type GradeFilterOption,
  type MicroIndexEntry,
  type FakeHadithCategory,
  type FakeHadithCategoryMeta,
  type FakeHadithItem,
  type AuthenticityCheckResult,
  type HadithState,
} from '@/features/hadith';

export * from '@/features/hadith';
