export interface SurahMeta {
  number: number;
  nameAr: string;
  nameEn: string;
  nameTranslation: string;
  revelationType: 'Meccan' | 'Medinan';
  numberOfAyahs: number;
  startPage: number;
  juz: number;
}

export interface QiraahMeta {
  id: string;
  name: string;
  narrator: string;
  origin: string;
  description: string;
  pdfUrl: string;
  featured?: boolean;
}

const HF_BASE = 'https://huggingface.co/datasets/hozifa1/islamic_books/resolve/main/books/Alqiraat_Quran';

export const QIRAAT_LIST: QiraahMeta[] = [
  {
    id: 'hafs',
    name: 'مصحف المدينة النبوية - رواية حفص عن عاصم',
    narrator: 'حفص بن سليمان الكوفي عن عاصم بن أبي النجود',
    origin: 'طريق الشاطبية - الرواية المعتمدة في مجمع الملك فهد',
    description: 'المصحف الشريف بالرسم العثماني المتقن بخط عثمان طه برواية حفص عن عاصم.',
    pdfUrl: `${HF_BASE}/quran_shoaba_from_asem.pdf`, // Paired with Aasim
    featured: true,
  },
  {
    id: 'warsh',
    name: 'مصحف القرآن الكريم - رواية ورش عن نافع',
    narrator: 'عثمان بن سعيد المصري (ورش) عن الإمام نافع المدني',
    origin: 'طريق الأزرق - الرواية السائدة في المغرب العربي وغرب إفريقيا',
    description: 'مصحف كامل ومحقق برواية ورش عن نافع بالرسم العثماني والمغربي المعتمد.',
    pdfUrl: `${HF_BASE}/quran_warsh.pdf`,
    featured: true,
  },
  {
    id: 'qaloon',
    name: 'مصحف القرآن الكريم - رواية قالون عن نافع',
    narrator: 'أبو موسى عيسى بن مينا (قالون) عن الإمام نافع المدني',
    origin: 'الرواية المشهورة في ليبيا وتونس وبعض بلدان إفريقيا',
    description: 'المصحف الشريف بقصر المنفصل وإسكان ميم الجمع وصلتها وضبط العلامات.',
    pdfUrl: `${HF_BASE}/quran_qalon.pdf`,
    featured: true,
  },
  {
    id: 'shoaba',
    name: 'مصحف القرآن الكريم - رواية شعبة عن عاصم',
    narrator: 'شعبة بن عياش الكوفي عن الإمام عاصم بن أبي النجود',
    origin: 'الرواية المقابلة لرواية حفص عن شيخهما الإمام عاصم',
    description: 'مصحف برواية شعبة من طريق الشاطبية ببيان الفروق الدقيقة في الكلمات والفرش.',
    pdfUrl: `${HF_BASE}/quran_shoaba_from_asem.pdf`,
    featured: true,
  },
  {
    id: 'alsosi',
    name: 'مصحف القرآن الكريم - رواية السوسي عن أبي عمرو',
    narrator: 'أبو شعيب صالح بن زياد السوسي عن أبي عمرو البصري',
    origin: 'مشهورة برواية الإدغام الكبير للحروف المتقاربة والمتماثلة',
    description: 'مصحف متميز بضبط الإدغام الكبير وإبدال الهمز الساكن وتسهيل الهمزتين.',
    pdfUrl: `${HF_BASE}/quran_alsosi_from_abi_amr.pdf`,
    featured: true,
  },
  {
    id: 'aldori-alkesaei',
    name: 'مصحف القرآن الكريم - رواية الدوري عن الكسائي',
    narrator: 'حفص بن عمر الدوري عن الإمام علي بن حمزة الكسائي الكوفي',
    origin: 'قراءة الكوفة السابعة المتواترة',
    description: 'المصحف الكريم برواية الدوري عن الكسائي مع ضبط الإمالات المتميزة.',
    pdfUrl: `${HF_BASE}/quran_aldori_from_alkesaei.pdf`,
  },
  {
    id: 'bizey',
    name: 'مصحف القرآن الكريم - رواية البزي عن ابن كثير',
    narrator: 'أحمد بن محمد بن عبد الله البزي عن عبد الله بن كثير المكي',
    origin: 'قراءة إمام أهل مكة المكرمة في القراءات المتواترة',
    description: 'المصحف الشريف بصلة هاء الضمير وقصر المنفصل وإثبات ياءات الزوائد.',
    pdfUrl: `${HF_BASE}/quran_bizey_from_ibn_katheer.pdf`,
  },
  {
    id: 'qunble',
    name: 'مصحف القرآن الكريم - رواية قنبل عن ابن كثير',
    narrator: 'محمد بن عبد الرحمن المخزومي (قنبل) عن ابن كثير المكي',
    origin: 'قراءة مكة المكرمة - من أشهر الروايات المتواترة',
    description: 'مصحف كامل محقق برواية قنبل مع الضبط القرآني المتقن.',
    pdfUrl: `${HF_BASE}/quran_qunble_from_ibn_katheer.pdf`,
  },
  {
    id: 'khalaf',
    name: 'مصحف القرآن الكريم - رواية خلف عن حمزة',
    narrator: 'خلف بن هشام البزار عن الإمام حمزة بن حبيب الزيات الكوفي',
    origin: 'من القراءات السبع الكبرى - مشهورة بالسكت والتحقيق',
    description: 'مصحف برواية خلف عن حمزة بالسكت على المفصول والموصول والوقف بالهمز.',
    pdfUrl: `${HF_BASE}/quran_khalaf_from_hamza.pdf`,
  },
  {
    id: 'khalad',
    name: 'مصحف القرآن الكريم - رواية خلاد عن حمزة',
    narrator: 'خلاد بن خالد الصيرفي عن الإمام حمزة الكوفي',
    origin: 'قراءة الكوفة المعتمدة',
    description: 'مصحف برواية خلاد من طريق الشاطبية مع أحكام الإمالات والسكت.',
    pdfUrl: `${HF_BASE}/quran_khalad_from_hamza.pdf`,
  },
  {
    id: 'hisham',
    name: 'مصحف القرآن الكريم - رواية هشام عن ابن عامر',
    narrator: 'هشام بن عمار الدمشقي عن عبد الله بن عامر الشامي',
    origin: 'قراءة أهل الشام المتواترة',
    description: 'مصحف برواية هشام بن عمار عن ابن عامر الشامي بالرسم العثماني المعتمد.',
    pdfUrl: `${HF_BASE}/quran_hisham_from_ibn_amer.pdf`,
  },
  {
    id: 'ibn-zakwan',
    name: 'مصحف القرآن الكريم - رواية ابن ذكوان عن ابن عامر',
    narrator: 'عبد الله بن أحمد بن ذكوان الدمشقي عن ابن عامر الشامي',
    origin: 'قراءة أهل الشام - طريق الشاطبية',
    description: 'المصحف الشريف برواية ابن ذكوان مع ضبط السكتات والإمالات.',
    pdfUrl: `${HF_BASE}/quran_ibn_zakwan_from_ibn_amer.pdf`,
  },
  {
    id: 'abi-alhareth',
    name: 'مصحف القرآن الكريم - رواية أبي الحارث عن الكسائي',
    narrator: 'الليث بن خالد (أبو الحارث) عن الإمام الكسائي الكوفي',
    origin: 'قراءة الكوفة المعتمدة',
    description: 'المصحف الكريم برواية أبي الحارث عن الكسائي مع ضبط هاء التأنيث وما قبلها.',
    pdfUrl: `${HF_BASE}/quran_abi_alhareth_from_alkesaei.pdf`,
  },
  {
    id: 'ibn-wardan',
    name: 'مصحف القرآن الكريم - رواية ابن وردان عن أبي جعفر',
    narrator: 'عيسى بن وردان المدني عن الإمام أبي جعفر المدني',
    origin: 'القراءة الثامنة من القراءات العشر المتواترة',
    description: 'مصحف برواية ابن وردان عن أبي جعفر المدني مع إخفاء النون عند الخاء والغين.',
    pdfUrl: `${HF_BASE}/quran_ibn_wardan_from_abi_jaafar.pdf`,
  },
  {
    id: 'ibn-jammaz',
    name: 'مصحف القرآن الكريم - رواية ابن جماز عن أبي جعفر',
    narrator: 'سليمان بن مسلم بن جماز عن الإمام أبي جعفر المدني',
    origin: 'قراءة المدينة المنورة المتواترة',
    description: 'المصحف الشريف برواية ابن جماز بضبط المد المنفصل وتسهيل الهمز.',
    pdfUrl: `${HF_BASE}/quran_ibn_jamaz_from_abi_jaafar.pdf`,
  },
  {
    id: 'roways',
    name: 'مصحف القرآن الكريم - رواية رويس عن يعقوب',
    narrator: 'محمد بن المتوكل (رويس) عن الإمام يعقوب الحضرمي البصري',
    origin: 'القراءة التاسعة من القراءات العشر المتواترة',
    description: 'مصحف برواية رويس مع ضبط هاء الكناية وإدغام الحروف والوقف بهاء السكت.',
    pdfUrl: `${HF_BASE}/quran_roways_from_yaakob_alhadrami.pdf`,
  },
  {
    id: 'roh',
    name: 'مصحف القرآن الكريم - رواية روح عن يعقوب',
    narrator: 'روح بن عبد المؤمن البصري عن يعقوب الحضرمي',
    origin: 'قراءة البصرة المتواترة',
    description: 'مصحف برواية روح عن يعقوب الحضرمي بالرسم العثماني المتقن.',
    pdfUrl: `${HF_BASE}/quran_roh_from_yaakob_alhadrami.pdf`,
  },
  {
    id: 'ishak-waraq',
    name: 'مصحف القرآن الكريم - رواية إسحاق الوراق عن خلف العاشر',
    narrator: 'إسحاق بن إبراهيم الوراق عن الإمام خلف بن هشام البزار',
    origin: 'القراءة العاشرة من القراءات العشر المتواترة',
    description: 'مصحف برواية إسحاق الوراق مع تحقيق الهمزات والإدغام.',
    pdfUrl: `${HF_BASE}/quran_ishak_alwaraq_from_khalaf_albazar.pdf`,
  },
  {
    id: 'idrees-haddad',
    name: 'مصحف القرآن الكريم - رواية إدريس الحداد عن خلف العاشر',
    narrator: 'إدريس بن عبد الكريم الحداد عن الإمام خلف العاشر',
    origin: 'ختام القراءات العشر الكبرى المتواترة',
    description: 'المصحف الشريف برواية إدريس الحداد عن خلف البزار الكوفي.',
    pdfUrl: `${HF_BASE}/quran_idres_alhadad_from_khalaf_albazaz.pdf`,
  },
];

export const ALL_SURAHS: SurahMeta[] = [
  { number: 1, nameAr: 'الفاتحة', nameEn: 'Al-Fatihah', nameTranslation: 'فاتحة الكتاب', revelationType: 'Meccan', numberOfAyahs: 7, startPage: 1, juz: 1 },
  { number: 2, nameAr: 'البقرة', nameEn: 'Al-Baqarah', nameTranslation: 'البقرة', revelationType: 'Medinan', numberOfAyahs: 286, startPage: 2, juz: 1 },
  { number: 3, nameAr: 'آل عمران', nameEn: 'Ali \'Imran', nameTranslation: 'آل عمران', revelationType: 'Medinan', numberOfAyahs: 200, startPage: 50, juz: 3 },
  { number: 4, nameAr: 'النساء', nameEn: 'An-Nisa', nameTranslation: 'النساء', revelationType: 'Medinan', numberOfAyahs: 176, startPage: 77, juz: 4 },
  { number: 5, nameAr: 'المائدة', nameEn: 'Al-Ma\'idah', nameTranslation: 'المائدة', revelationType: 'Medinan', numberOfAyahs: 120, startPage: 106, juz: 6 },
  { number: 6, nameAr: 'الأنعام', nameEn: 'Al-An\'am', nameTranslation: 'الأنعام', revelationType: 'Meccan', numberOfAyahs: 165, startPage: 128, juz: 7 },
  { number: 7, nameAr: 'الأعراف', nameEn: 'Al-A\'raf', nameTranslation: 'الأعراف', revelationType: 'Meccan', numberOfAyahs: 206, startPage: 151, juz: 8 },
  { number: 8, nameAr: 'الأنفال', nameEn: 'Al-Anfal', nameTranslation: 'الأنفال', revelationType: 'Medinan', numberOfAyahs: 75, startPage: 177, juz: 9 },
  { number: 9, nameAr: 'التوبة', nameEn: 'At-Tawbah', nameTranslation: 'التوبة', revelationType: 'Medinan', numberOfAyahs: 129, startPage: 187, juz: 10 },
  { number: 10, nameAr: 'يونس', nameEn: 'Yunus', nameTranslation: 'يونس', revelationType: 'Meccan', numberOfAyahs: 109, startPage: 208, juz: 11 },
  { number: 11, nameAr: 'هود', nameEn: 'Hud', nameTranslation: 'هود', revelationType: 'Meccan', numberOfAyahs: 123, startPage: 221, juz: 11 },
  { number: 12, nameAr: 'يوسف', nameEn: 'Yusuf', nameTranslation: 'يوسف', revelationType: 'Meccan', numberOfAyahs: 111, startPage: 235, juz: 12 },
  { number: 13, nameAr: 'الرعد', nameEn: 'Ar-Ra\'d', nameTranslation: 'الرعد', revelationType: 'Medinan', numberOfAyahs: 43, startPage: 249, juz: 13 },
  { number: 14, nameAr: 'إبراهيم', nameEn: 'Ibrahim', nameTranslation: 'إبراهيم', revelationType: 'Meccan', numberOfAyahs: 52, startPage: 255, juz: 13 },
  { number: 15, nameAr: 'الحجر', nameEn: 'Al-Hijr', nameTranslation: 'الحجر', revelationType: 'Meccan', numberOfAyahs: 99, startPage: 262, juz: 14 },
  { number: 16, nameAr: 'النحل', nameEn: 'An-Nahl', nameTranslation: 'النحل', revelationType: 'Meccan', numberOfAyahs: 128, startPage: 267, juz: 14 },
  { number: 17, nameAr: 'الإسراء', nameEn: 'Al-Isra', nameTranslation: 'الإسراء', revelationType: 'Meccan', numberOfAyahs: 111, startPage: 282, juz: 15 },
  { number: 18, nameAr: 'الكهف', nameEn: 'Al-Kahf', nameTranslation: 'الكهف', revelationType: 'Meccan', numberOfAyahs: 110, startPage: 293, juz: 15 },
  { number: 19, nameAr: 'مريم', nameEn: 'Maryam', nameTranslation: 'مريم', revelationType: 'Meccan', numberOfAyahs: 98, startPage: 305, juz: 16 },
  { number: 20, nameAr: 'طه', nameEn: 'Ta-Ha', nameTranslation: 'طه', revelationType: 'Meccan', numberOfAyahs: 135, startPage: 312, juz: 16 },
  { number: 21, nameAr: 'الأنبياء', nameEn: 'Al-Anbiya', nameTranslation: 'الأنبياء', revelationType: 'Meccan', numberOfAyahs: 112, startPage: 322, juz: 17 },
  { number: 22, nameAr: 'الحج', nameEn: 'Al-Hajj', nameTranslation: 'الحج', revelationType: 'Medinan', numberOfAyahs: 78, startPage: 332, juz: 17 },
  { number: 23, nameAr: 'المؤمنون', nameEn: 'Al-Mu\'minun', nameTranslation: 'المؤمنون', revelationType: 'Meccan', numberOfAyahs: 118, startPage: 342, juz: 18 },
  { number: 24, nameAr: 'النور', nameEn: 'An-Nur', nameTranslation: 'النور', revelationType: 'Medinan', numberOfAyahs: 64, startPage: 350, juz: 18 },
  { number: 25, nameAr: 'الفرقان', nameEn: 'Al-Furqan', nameTranslation: 'الفرقان', revelationType: 'Meccan', numberOfAyahs: 77, startPage: 359, juz: 18 },
  { number: 26, nameAr: 'الشعراء', nameEn: 'Ash-Shu\'ara', nameTranslation: 'الشعراء', revelationType: 'Meccan', numberOfAyahs: 227, startPage: 367, juz: 19 },
  { number: 27, nameAr: 'النمل', nameEn: 'An-Naml', nameTranslation: 'النمل', revelationType: 'Meccan', numberOfAyahs: 93, startPage: 377, juz: 19 },
  { number: 28, nameAr: 'القصص', nameEn: 'Al-Qasas', nameTranslation: 'القصص', revelationType: 'Meccan', numberOfAyahs: 88, startPage: 385, juz: 20 },
  { number: 29, nameAr: 'العنكبوت', nameEn: 'Al-\'Ankabut', nameTranslation: 'العنكبوت', revelationType: 'Meccan', numberOfAyahs: 69, startPage: 396, juz: 20 },
  { number: 30, nameAr: 'الروم', nameEn: 'Ar-Rum', nameTranslation: 'الروم', revelationType: 'Meccan', numberOfAyahs: 60, startPage: 404, juz: 21 },
  { number: 31, nameAr: 'لقمان', nameEn: 'Luqman', nameTranslation: 'لقمان', revelationType: 'Meccan', numberOfAyahs: 34, startPage: 411, juz: 21 },
  { number: 32, nameAr: 'السجدة', nameEn: 'As-Sajdah', nameTranslation: 'السجدة', revelationType: 'Meccan', numberOfAyahs: 30, startPage: 415, juz: 21 },
  { number: 33, nameAr: 'الأحزاب', nameEn: 'Al-Ahzab', nameTranslation: 'الأحزاب', revelationType: 'Medinan', numberOfAyahs: 73, startPage: 418, juz: 21 },
  { number: 34, nameAr: 'سبأ', nameEn: 'Saba', nameTranslation: 'سبأ', revelationType: 'Meccan', numberOfAyahs: 54, startPage: 428, juz: 22 },
  { number: 35, nameAr: 'فاطر', nameEn: 'Fatir', nameTranslation: 'فاطر', revelationType: 'Meccan', numberOfAyahs: 45, startPage: 434, juz: 22 },
  { number: 36, nameAr: 'يس', nameEn: 'Ya-Sin', nameTranslation: 'يس', revelationType: 'Meccan', numberOfAyahs: 83, startPage: 440, juz: 22 },
  { number: 37, nameAr: 'الصافات', nameEn: 'As-Saffat', nameTranslation: 'الصافات', revelationType: 'Meccan', numberOfAyahs: 182, startPage: 446, juz: 23 },
  { number: 38, nameAr: 'ص', nameEn: 'Sad', nameTranslation: 'ص', revelationType: 'Meccan', numberOfAyahs: 88, startPage: 453, juz: 23 },
  { number: 39, nameAr: 'الزمر', nameEn: 'Az-Zumar', nameTranslation: 'الزمر', revelationType: 'Meccan', numberOfAyahs: 75, startPage: 458, juz: 23 },
  { number: 40, nameAr: 'غافر', nameEn: 'Ghafir', nameTranslation: 'غافر', revelationType: 'Meccan', numberOfAyahs: 85, startPage: 467, juz: 24 },
  { number: 41, nameAr: 'فصلت', nameEn: 'Fussilat', nameTranslation: 'فصلت', revelationType: 'Meccan', numberOfAyahs: 54, startPage: 477, juz: 24 },
  { number: 42, nameAr: 'الشورى', nameEn: 'Ash-Shura', nameTranslation: 'الشورى', revelationType: 'Meccan', numberOfAyahs: 53, startPage: 483, juz: 25 },
  { number: 43, nameAr: 'الزخرف', nameEn: 'Az-Zukhruf', nameTranslation: 'الزخرف', revelationType: 'Meccan', numberOfAyahs: 89, startPage: 489, juz: 25 },
  { number: 44, nameAr: 'الدخان', nameEn: 'Ad-Dukhan', nameTranslation: 'الدخان', revelationType: 'Meccan', numberOfAyahs: 59, startPage: 496, juz: 25 },
  { number: 45, nameAr: 'الجاثية', nameEn: 'Al-Jathiyah', nameTranslation: 'الجاثية', revelationType: 'Meccan', numberOfAyahs: 37, startPage: 499, juz: 25 },
  { number: 46, nameAr: 'الأحقاف', nameEn: 'Al-Ahqaf', nameTranslation: 'الأحقاف', revelationType: 'Meccan', numberOfAyahs: 35, startPage: 502, juz: 26 },
  { number: 47, nameAr: 'محمد', nameEn: 'Muhammad', nameTranslation: 'محمد', revelationType: 'Medinan', numberOfAyahs: 38, startPage: 507, juz: 26 },
  { number: 48, nameAr: 'الفتح', nameEn: 'Al-Fath', nameTranslation: 'الفتح', revelationType: 'Medinan', numberOfAyahs: 29, startPage: 511, juz: 26 },
  { number: 49, nameAr: 'الحجرات', nameEn: 'Al-Hujurat', nameTranslation: 'الحجرات', revelationType: 'Medinan', numberOfAyahs: 18, startPage: 515, juz: 26 },
  { number: 50, nameAr: 'ق', nameEn: 'Qaf', nameTranslation: 'ق', revelationType: 'Meccan', numberOfAyahs: 45, startPage: 518, juz: 26 },
  { number: 51, nameAr: 'الذاريات', nameEn: 'Adh-Dhariyat', nameTranslation: 'الذاريات', revelationType: 'Meccan', numberOfAyahs: 60, startPage: 520, juz: 26 },
  { number: 52, nameAr: 'الطور', nameEn: 'At-Tur', nameTranslation: 'الطور', revelationType: 'Meccan', numberOfAyahs: 49, startPage: 523, juz: 27 },
  { number: 53, nameAr: 'النجم', nameEn: 'An-Najm', nameTranslation: 'النجم', revelationType: 'Meccan', numberOfAyahs: 62, startPage: 526, juz: 27 },
  { number: 54, nameAr: 'القمر', nameEn: 'Al-Qamar', nameTranslation: 'القمر', revelationType: 'Meccan', numberOfAyahs: 55, startPage: 528, juz: 27 },
  { number: 55, nameAr: 'الرحمن', nameEn: 'Ar-Rahman', nameTranslation: 'الرحمن', revelationType: 'Medinan', numberOfAyahs: 78, startPage: 531, juz: 27 },
  { number: 56, nameAr: 'الواقعة', nameEn: 'Al-Waqi\'ah', nameTranslation: 'الواقعة', revelationType: 'Meccan', numberOfAyahs: 96, startPage: 534, juz: 27 },
  { number: 57, nameAr: 'الحديد', nameEn: 'Al-Hadid', nameTranslation: 'الحديد', revelationType: 'Medinan', numberOfAyahs: 29, startPage: 537, juz: 27 },
  { number: 58, nameAr: 'المجادلة', nameEn: 'Al-Mujadila', nameTranslation: 'المجادلة', revelationType: 'Medinan', numberOfAyahs: 22, startPage: 542, juz: 28 },
  { number: 59, nameAr: 'الحشر', nameEn: 'Al-Hashr', nameTranslation: 'الحشر', revelationType: 'Medinan', numberOfAyahs: 24, startPage: 545, juz: 28 },
  { number: 60, nameAr: 'الممتحنة', nameEn: 'Al-Mumtahanah', nameTranslation: 'الممتحنة', revelationType: 'Medinan', numberOfAyahs: 13, startPage: 549, juz: 28 },
  { number: 61, nameAr: 'الصف', nameEn: 'As-Saf', nameTranslation: 'الصف', revelationType: 'Medinan', numberOfAyahs: 14, startPage: 551, juz: 28 },
  { number: 62, nameAr: 'الجمعة', nameEn: 'Al-Jumu\'ah', nameTranslation: 'الجمعة', revelationType: 'Medinan', numberOfAyahs: 11, startPage: 553, juz: 28 },
  { number: 63, nameAr: 'المنافقون', nameEn: 'Al-Munafiqun', nameTranslation: 'المنافقون', revelationType: 'Medinan', numberOfAyahs: 11, startPage: 554, juz: 28 },
  { number: 64, nameAr: 'التغابن', nameEn: 'At-Taghabun', nameTranslation: 'التغابن', revelationType: 'Medinan', numberOfAyahs: 18, startPage: 556, juz: 28 },
  { number: 65, nameAr: 'الطلاق', nameEn: 'At-Talaq', nameTranslation: 'الطلاق', revelationType: 'Medinan', numberOfAyahs: 12, startPage: 558, juz: 28 },
  { number: 66, nameAr: 'التحريم', nameEn: 'At-Tahrim', nameTranslation: 'التحريم', revelationType: 'Medinan', numberOfAyahs: 12, startPage: 560, juz: 28 },
  { number: 67, nameAr: 'الملك', nameEn: 'Al-Mulk', nameTranslation: 'الملك', revelationType: 'Meccan', numberOfAyahs: 30, startPage: 562, juz: 29 },
  { number: 68, nameAr: 'القلم', nameEn: 'Al-Qalam', nameTranslation: 'القلم', revelationType: 'Meccan', numberOfAyahs: 52, startPage: 564, juz: 29 },
  { number: 69, nameAr: 'الحاقة', nameEn: 'Al-Haqqah', nameTranslation: 'الحاقة', revelationType: 'Meccan', numberOfAyahs: 52, startPage: 566, juz: 29 },
  { number: 70, nameAr: 'المعارج', nameEn: 'Al-Ma\'arij', nameTranslation: 'المعارج', revelationType: 'Meccan', numberOfAyahs: 44, startPage: 568, juz: 29 },
  { number: 71, nameAr: 'نوح', nameEn: 'Nuh', nameTranslation: 'نوح', revelationType: 'Meccan', numberOfAyahs: 28, startPage: 570, juz: 29 },
  { number: 72, nameAr: 'الجن', nameEn: 'Al-Jinn', nameTranslation: 'الجن', revelationType: 'Meccan', numberOfAyahs: 28, startPage: 572, juz: 29 },
  { number: 73, nameAr: 'المزمل', nameEn: 'Al-Muzzammil', nameTranslation: 'المزمل', revelationType: 'Meccan', numberOfAyahs: 20, startPage: 574, juz: 29 },
  { number: 74, nameAr: 'المدثر', nameEn: 'Al-Muddaththir', nameTranslation: 'المدثر', revelationType: 'Meccan', numberOfAyahs: 56, startPage: 575, juz: 29 },
  { number: 75, nameAr: 'القيامة', nameEn: 'Al-Qiyamah', nameTranslation: 'القيامة', revelationType: 'Meccan', numberOfAyahs: 40, startPage: 577, juz: 29 },
  { number: 76, nameAr: 'الإنسان', nameEn: 'Al-Insan', nameTranslation: 'الإنسان', revelationType: 'Medinan', numberOfAyahs: 31, startPage: 578, juz: 29 },
  { number: 77, nameAr: 'المرسلات', nameEn: 'Al-Mursalat', nameTranslation: 'المرسلات', revelationType: 'Meccan', numberOfAyahs: 50, startPage: 580, juz: 29 },
  { number: 78, nameAr: 'النبأ', nameEn: 'An-Naba', nameTranslation: 'النبأ', revelationType: 'Meccan', numberOfAyahs: 40, startPage: 582, juz: 30 },
  { number: 79, nameAr: 'النازعات', nameEn: 'An-Nazi\'at', nameTranslation: 'النازعات', revelationType: 'Meccan', numberOfAyahs: 46, startPage: 583, juz: 30 },
  { number: 80, nameAr: 'عبس', nameEn: '\'Abasa', nameTranslation: 'عبس', revelationType: 'Meccan', numberOfAyahs: 42, startPage: 585, juz: 30 },
  { number: 81, nameAr: 'التكوير', nameEn: 'At-Takwir', nameTranslation: 'التكوير', revelationType: 'Meccan', numberOfAyahs: 29, startPage: 586, juz: 30 },
  { number: 82, nameAr: 'الانفطار', nameEn: 'Al-Infitar', nameTranslation: 'الانفطار', revelationType: 'Meccan', numberOfAyahs: 19, startPage: 587, juz: 30 },
  { number: 83, nameAr: 'المطففين', nameEn: 'Al-Mutaffifin', nameTranslation: 'المطففين', revelationType: 'Meccan', numberOfAyahs: 36, startPage: 587, juz: 30 },
  { number: 84, nameAr: 'الانشقاق', nameEn: 'Al-Inshiqaq', nameTranslation: 'الانشقاق', revelationType: 'Meccan', numberOfAyahs: 25, startPage: 589, juz: 30 },
  { number: 85, nameAr: 'البروج', nameEn: 'Al-Buruj', nameTranslation: 'البروج', revelationType: 'Meccan', numberOfAyahs: 22, startPage: 590, juz: 30 },
  { number: 86, nameAr: 'الطارق', nameEn: 'At-Tariq', nameTranslation: 'الطارق', revelationType: 'Meccan', numberOfAyahs: 17, startPage: 591, juz: 30 },
  { number: 87, nameAr: 'الأعلى', nameEn: 'Al-A\'la', nameTranslation: 'الأعلى', revelationType: 'Meccan', numberOfAyahs: 19, startPage: 591, juz: 30 },
  { number: 88, nameAr: 'الغاشية', nameEn: 'Al-Ghashiyah', nameTranslation: 'الغاشية', revelationType: 'Meccan', numberOfAyahs: 26, startPage: 592, juz: 30 },
  { number: 89, nameAr: 'الفجر', nameEn: 'Al-Fajr', nameTranslation: 'الفجر', revelationType: 'Meccan', numberOfAyahs: 30, startPage: 593, juz: 30 },
  { number: 90, nameAr: 'البلد', nameEn: 'Al-Balad', nameTranslation: 'البلد', revelationType: 'Meccan', numberOfAyahs: 20, startPage: 594, juz: 30 },
  { number: 91, nameAr: 'الشمس', nameEn: 'Ash-Shams', nameTranslation: 'الشمس', revelationType: 'Meccan', numberOfAyahs: 15, startPage: 595, juz: 30 },
  { number: 92, nameAr: 'الليل', nameEn: 'Al-Layl', nameTranslation: 'الليل', revelationType: 'Meccan', numberOfAyahs: 21, startPage: 595, juz: 30 },
  { number: 93, nameAr: 'الضحى', nameEn: 'Ad-Duha', nameTranslation: 'الضحى', revelationType: 'Meccan', numberOfAyahs: 11, startPage: 596, juz: 30 },
  { number: 94, nameAr: 'الشرح', nameEn: 'Ash-Sharh', nameTranslation: 'الشرح', revelationType: 'Meccan', numberOfAyahs: 8, startPage: 596, juz: 30 },
  { number: 95, nameAr: 'التين', nameEn: 'At-Tin', nameTranslation: 'التين', revelationType: 'Meccan', numberOfAyahs: 8, startPage: 597, juz: 30 },
  { number: 96, nameAr: 'العلق', nameEn: 'Al-\'Alaq', nameTranslation: 'العلق', revelationType: 'Meccan', numberOfAyahs: 19, startPage: 597, juz: 30 },
  { number: 97, nameAr: 'القدر', nameEn: 'Al-Qadr', nameTranslation: 'القدر', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 598, juz: 30 },
  { number: 98, nameAr: 'البينة', nameEn: 'Al-Bayyinah', nameTranslation: 'البينة', revelationType: 'Medinan', numberOfAyahs: 8, startPage: 598, juz: 30 },
  { number: 99, nameAr: 'الزلزلة', nameEn: 'Az-Zalzalah', nameTranslation: 'الزلزلة', revelationType: 'Medinan', numberOfAyahs: 8, startPage: 599, juz: 30 },
  { number: 100, nameAr: 'العاديات', nameEn: 'Al-\'Adiyat', nameTranslation: 'العاديات', revelationType: 'Meccan', numberOfAyahs: 11, startPage: 599, juz: 30 },
  { number: 101, nameAr: 'القارعة', nameEn: 'Al-Qari\'ah', nameTranslation: 'القارعة', revelationType: 'Meccan', numberOfAyahs: 11, startPage: 600, juz: 30 },
  { number: 102, nameAr: 'التكاثر', nameEn: 'At-Takathur', nameTranslation: 'التكاثر', revelationType: 'Meccan', numberOfAyahs: 8, startPage: 600, juz: 30 },
  { number: 103, nameAr: 'العصر', nameEn: 'Al-\'Asr', nameTranslation: 'العصر', revelationType: 'Meccan', numberOfAyahs: 3, startPage: 601, juz: 30 },
  { number: 104, nameAr: 'الهمزة', nameEn: 'Al-Humazah', nameTranslation: 'الهمزة', revelationType: 'Meccan', numberOfAyahs: 9, startPage: 601, juz: 30 },
  { number: 105, nameAr: 'الفيل', nameEn: 'Al-Fil', nameTranslation: 'الفيل', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 601, juz: 30 },
  { number: 106, nameAr: 'قريش', nameEn: 'Quraysh', nameTranslation: 'قريش', revelationType: 'Meccan', numberOfAyahs: 4, startPage: 602, juz: 30 },
  { number: 107, nameAr: 'الماعون', nameEn: 'Al-Ma\'un', nameTranslation: 'الماعون', revelationType: 'Meccan', numberOfAyahs: 7, startPage: 602, juz: 30 },
  { number: 108, nameAr: 'الكوثر', nameEn: 'Al-Kawthar', nameTranslation: 'الكوثر', revelationType: 'Meccan', numberOfAyahs: 3, startPage: 602, juz: 30 },
  { number: 109, nameAr: 'الكافرون', nameEn: 'Al-Kafirun', nameTranslation: 'الكافرون', revelationType: 'Meccan', numberOfAyahs: 6, startPage: 603, juz: 30 },
  { number: 110, nameAr: 'النصر', nameEn: 'An-Nasr', nameTranslation: 'النصر', revelationType: 'Medinan', numberOfAyahs: 3, startPage: 603, juz: 30 },
  { number: 111, nameAr: 'المسد', nameEn: 'Al-Masad', nameTranslation: 'المسد', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 603, juz: 30 },
  { number: 112, nameAr: 'الإخلاص', nameEn: 'Al-Ikhlas', nameTranslation: 'الإخلاص', revelationType: 'Meccan', numberOfAyahs: 4, startPage: 604, juz: 30 },
  { number: 113, nameAr: 'الفلق', nameEn: 'Al-Falaq', nameTranslation: 'الفلق', revelationType: 'Meccan', numberOfAyahs: 5, startPage: 604, juz: 30 },
  { number: 114, nameAr: 'الناس', nameEn: 'An-Nas', nameTranslation: 'الناس', revelationType: 'Meccan', numberOfAyahs: 6, startPage: 604, juz: 30 },
];

export interface QuranTranslationMeta {
  code: string;
  name: string;
  nativeName: string;
  author: string;
  direction: 'ltr' | 'rtl';
  fileKey: string;
}

export const QURAN_TRANSLATIONS: QuranTranslationMeta[] = [
  { code: 'en-saheeh', name: 'الإنجليزية (صحيح إنترناشونال)', nativeName: 'English (Saheeh Int.)', author: 'Saheeh International', direction: 'ltr', fileKey: 'quran_en_english_saheeh.json' },
  { code: 'en-hilali', name: 'الإنجليزية (الهلالي وخان)', nativeName: 'English (Hilali & Khan)', author: 'Taqi-ud-Din al-Hilali & Muhsin Khan', direction: 'ltr', fileKey: 'quran_en_english_hilali_khan.json' },
  { code: 'fr-montada', name: 'الفرنسية (المنتدى الإسلامي)', nativeName: 'Français (Montada)', author: 'Montada Islamic Center', direction: 'ltr', fileKey: 'quran_fr_french_montada.json' },
  { code: 'de-bubenheim', name: 'الألمانية (بوبنهايم)', nativeName: 'Deutsch (Bubenheim)', author: 'Frank Bubenheim & Nadeem Elyas', direction: 'ltr', fileKey: 'quran_de_german_bubenheim.json' },
  { code: 'es-garcia', name: 'الإسبانية (غارسيا)', nativeName: 'Español (García)', author: 'Muhammad Isa García', direction: 'ltr', fileKey: 'quran_es_spanish_garcia.json' },
  { code: 'tr-rwwad', name: 'التركية (رواد الترجمة)', nativeName: 'Türkçe (Rwwad)', author: 'Rwwad Translation Center', direction: 'ltr', fileKey: 'quran_tr_turkish_rwwad.json' },
  { code: 'ur-junagarhi', name: 'الأردية (جوناكارهي)', nativeName: 'اردو (مولانا جوناگڑھی)', author: 'Maulana Muhammad Junagarhi', direction: 'rtl', fileKey: 'quran_ur_urdu_junagarhi.json' },
  { code: 'id-affairs', name: 'الإندونيسية (وزارة الشؤون الدينية)', nativeName: 'Bahasa Indonesia (Kemenag)', author: 'Indonesian Ministry of Religious Affairs', direction: 'ltr', fileKey: 'quran_id_indonesian_affairs.json' },
  { code: 'zh-makin', name: 'الصينية (محمد مكين)', nativeName: '中文 (马坚)', author: 'Muhammad Makin', direction: 'ltr', fileKey: 'quran_zh_chinese_makin.json' },
  { code: 'ru-kuliev', name: 'الروسية (إسلام هاوس)', nativeName: 'Русский', author: 'IslamHouse Russian Team', direction: 'ltr', fileKey: 'islamhouse_quran_ru.json' },
];
